// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7U2cWfta5hmhQmofLZnk0wCxK5VgiRk',
    appId: '1:401384632441:android:2bc63dca97c1215afb24a8',
    messagingSenderId: '401384632441',
    projectId: 'todolist-c975c',
    databaseURL: 'https://todolist-c975c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-c975c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrh-2AjaqM7zaoKfMpLu4ToRxFKK1Kjd8',
    appId: '1:401384632441:web:4c05172a22bed9bdfb24a8',
    messagingSenderId: '401384632441',
    projectId: 'todolist-c975c',
    authDomain: 'todolist-c975c.firebaseapp.com',
    databaseURL: 'https://todolist-c975c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-c975c.appspot.com',
    measurementId: 'G-0EHSZTL099',
  );
}
